apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
spec:
  serviceName: "postgres-master-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: master
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      containers:
        - name: postgres
          image: bitnami/postgres:latest
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: pg-master-data
              mountPath: /bitnami/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-master-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
